### ISSUE TITLE
[Security Issue] .env file

### ISSUE THREAD

**Issue by fozooni** [mohsenxad/sep-payment-gateway#3]
Hi dear,

I am looking for a typescript-support package and randomly I faced your repository. Mistakenly, you pushed your `.env` file. Your Merchant Security code appears there.

I just wanted to share this notice with you.

Wish you best

**Comment by mohsenxad** [comment]
hey man

thanks for the hint 🏆
i remove the secret from all commits

**Comment by fozooni** [comment]
Hi again,

Sorry I just forget to check the response on the time.
Your welcome bro ☺️

Wish you bests
